### ISSUE TITLE
Nullpointer when starting a flow

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#272]
When creating a simple file to file interface the following error occurs

ath getFlowConfiguration for gateway with id 1
error.uri => file://C:\Messages\error
flow.maximumRedeliveries => 0
flow.name => TestFlow
flow.offloading => false
flow.redeliveryDelay => 3000
flow.type => default
from.uri => file://C:\Messages\in
id => 1
offramp.uri.list => direct:flow=1endpoint=1
to.1.uri => file://C:\Messages\out
2019-10-22 13:51:19.215 DEBUG 60728 --- [  XNIO-2 task-1] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/setflowconfiguration/{id} for gateway with id 1
2019-10-22 13:51:19.215  INFO 60728 --- [  XNIO-2 task-3] o.a.c.connect.impl.CamelConnector        : Start flow 1
2019-10-22 13:51:19.215  INFO 60728 --- [  XNIO-2 task-3] o.a.c.connect.impl.CamelConnector        : Adding route with id: 1
2019-10-22 13:51:19.215  INFO 60728 --- [  XNIO-2 task-3] o.a.c.connect.impl.CamelConnector        : Add default flow
2019-10-22 13:51:19.215  INFO 60728 --- [  XNIO-2 task-3] o.a.connector.routes.DefaultRoute        : Configuring default route
2019-10-22 13:51:19.306  INFO 60728 --- [  XNIO-2 task-3] o.a.c.connect.impl.CamelConnector        : Started flow 1
2019-10-22 13:51:19.307 DEBUG 60728 --- [  XNIO-2 task-3] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/flow/start/{id} for gateway with id 1
2019-10-22 13:51:19.317 DEBUG 60728 --- [  XNIO-2 task-6] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/flow/stats/{id} for gateway with id 1
2019-10-22 13:51:19.324 DEBUG 60728 --- [  XNIO-2 task-2] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/flow/stats/{id} for gateway with id 1
2019-10-22 13:51:19.334 DEBUG 60728 --- [  XNIO-2 task-8] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/flow/stats/{id} for gateway with id 1
2019-10-22 13:51:20.262 ERROR 60728 --- [5CMessages%5Cin] o.a.connector.routes.DefaultRoute        : Failed delivery for (MessageId: ID-LP238-1571736655024-0-10 on ExchangeId: ID-LP238-1571736655024-0-9). Exhausted after delivery attempt: 1 caught: java.lang.NullPointerException. Handled by DeadLetterChannel: [file://C:%5CMessages%5Cerror]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[1                 ] [1                 ] [file://C:%5CMessages%5Cin                                                     ] [         0]
[1                 ] [setHeader11       ] [setHeader[AssimblyFlowID]                                                     ] [         0]
[1                 ] [setHeader12       ] [setHeader[AssimblyHeaderId]                                                   ] [         0]
[1                 ] [setHeader13       ] [setHeader[AssimblyFrom]                                                       ] [         0]
[1                 ] [process5          ] [Processor@0x685ea995                                                          ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

java.lang.NullPointerException: null
        at org.assimbly.connector.routes.DefaultRoute$SetHeaders.process(DefaultRoute.java:198)
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:454)
        at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:223)
        at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:187)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

2019-10-22 13:51:20.277 DEBUG 60728 --- [  XNIO-2 task-7] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/flow/failedlogentries/{id} for gateway with id 1
2019-10-22 13:51:20.277 DEBUG 60728 --- [  XNIO-2 task-5] o.a.gateway.web.rest.util.ResponseUtil   : REST request with path /connector/{connectorId}/flow/failedlogentries/{id} for gateway with id 1
2019-10-22 13:51:20.277 ERROR 60728 --- [5CMessages%5Cin] o.a.connector.routes.DefaultRoute        : Failed delivery for (MessageId: ID-LP238-1571736655024-0-12 on ExchangeId: ID-LP238-1571736655024-0-11). Exhausted after delivery attempt: 1 caught: java.lang.NullPointerException. Handled by DeadLetterChannel: [file://C:%5CMessages%5Cerror]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[1                 ] [1                 ] [file://C:%5CMessages%5Cin                                                     ] [         0]
[1                 ] [setHeader11       ] [setHeader[AssimblyFlowID]                                                     ] [         0]
[1                 ] [setHeader12       ] [setHeader[AssimblyHeaderId]                                                   ] [         0]
[1                 ] [setHeader13       ] [setHeader[AssimblyFrom]                                                       ] [         0]
[1                 ] [process5          ] [Processor@0x685ea995                                                          ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

java.lang.NullPointerException: null
        at org.assimbly.connector.routes.DefaultRoute$SetHeaders.process(DefaultRoute.java:198)
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:454)
        at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:223)
        at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:187)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by assimbly** [comment]
Fixed
