### ISSUE TITLE
Next-temp - Dovetail login fails

### ISSUE THREAD

**Issue by brunovg** [assimbly/gateway#839]
Problems on the frontend login (Dovetail).
The problem only occurs on Next-temp (temporary server deploy).

The error log on Assimbly:
```
Caused by: java.lang.NoSuchMethodError: 'org.hibernate.proxy.LazyInitializer org.hibernate.proxy.HibernateProxy.extractLazyInitializer(java.lang.Object)'
	at org.hibernate.jpa.internal.util.PersistenceUtilHelper.isLoadedWithoutReference(PersistenceUtilHelper.java:125)
	at org.hibernate.jpa.HibernatePersistenceProvider$1.isLoadedWithoutReference(HibernatePersistenceProvider.java:185)
	at jakarta.persistence.Persistence$PersistenceUtilImpl.isLoaded(Persistence.java:145)
```

**Comment by brunovg** [comment]
It seems that smooksnoxml uses an old version of hibernate (4.3.8.Final),
```
milyn-smooks-all 1.7.1  >  milyn-scribe-hibernate 1.7.1  >  hibernate-core 4.3.8
```

and that old version was loaded instead of a more recent one (6.5.2.Final) added by the gateway.

**Comment by brunovg** [comment]
PR: https://github.com/assimbly/custom-components/pull/102
